version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - 5000:8000
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - activo-api

  postgres-db:
    image: arm64v8/postgres:12-alpine
    ports:
      - 4321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - activo-api

networks:
  activo-api:
    driver: bridge

volumes:
  postgres_data:
