# Generated by Django 3.2 on 2021-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='should_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
